apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
     - hard
     - nfsvers=4
  nfs:
    path: /zpool/k3s-storage
    server: 10.7.7.110