# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nfs
# spec:
#   capacity:
#     storage: 500Mi
#   accessModes:
#     - ReadWriteMany
#   storageClassName: nfs
#   nfs:
#     server: 10.7.7.110
#     path: "/zpool/k3s-storage"
#####
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 500Mi
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  #persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
     - hard
     - nfsvers=4
  nfs:
    path: /zpool/k3s-storage
    server: 10.7.7.110