# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nfs
# spec:
#   accessModes: 
#     - ReadWriteMany
#   storageClassName: nfs
#   resources:
#     requests:
#       storage: 100Mi
###

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  storageClassName: nfs
  resources:
    requests:
      storage: 100Mi
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    
