apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-backup
  namespace: vault
spec:
  schedule: "0 * * * *"  # every hour
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: vault-backup
          containers:
            - name: backup
              image: hashicorp/vault:1.13.3
              command:
                - /bin/sh
                - -c
                - |
                  export VAULT_ADDR=http://vault:8200
                  JWT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
                  VAULT_TOKEN=$(vault write -field=token auth/kubernetes/login role=vault-backup jwt=$JWT)
                  vault login $VAULT_TOKEN
                  vault operator raft snapshot save /vault/backups/snapshot-$(date +%Y%m%d%H%M).snap
              volumeMounts:
                - name: vault-backup
                  mountPath: /vault/backups
          restartPolicy: OnFailure
          volumes:
            - name: vault-backup
              persistentVolumeClaim:
                claimName: vault-backup-pvc
