apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-backup-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vault-nfs
  mountOptions:
     - hard
     - nfsvers=4
  nfs:
    path: /zpool/k3s-storage/vaults-backup
    server: 10.7.7.110