services:
  monitoring:
    container_name: glances
    image: nicolargo/glances:latest
    restart: always
    ports:
      - 61208:61208
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Uncomment the below line if you want glances to display host OS detail instead of container's
      - /etc/os-release:/etc/os-release:ro
    environment:
      - "GLANCES_OPT=-w"