# networks:
#   frontend:
#     external: true
#     name: frontend

volumes:
  uptimekuma:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    restart: always
    container_name: uptime-kuma
    volumes:
      - uptimekuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    networks:
      - frontend