apiVersion: apps/v1
kind: Deployment
metadata:
  name: [name]
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: [appName]
  template:
    metadata:
      labels:
        app: [appName]
    spec:
      containers:
        - name: [containerName]
          image: [imageName]
          volumeMounts:
            - mountPath: [containerWorkDir]
              name: [volumeName]
      volumes:
        - name: [volumeName]
          # emptyDir: {}
          persistentVolumeClaim:
            claimName: [host-pvc-name]