# These Resource Limits are in line with node requirements in the
# Vault Reference Architecture for a Small Cluster
server:
  resources:
    requests:
      memory: 2Gi
      cpu: 250m
    limits:
      memory: 4Gi
      cpu: 250m

  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: local-path  # or whatever you use for normal storage
  
  config: |
    storage "raft" {
      path    = "/vault/data"
      node_id = "$(POD_NAME)"
    }

    service_registration "kubernetes" {}

  extraVolumes:
    - name: vault-backup
      persistentVolumeClaim:
        claimName: vault-backup-pvc

  extraVolumeMounts:
    - name: vault-backup
      mountPath: /vault/backups
  
  # dev:
  #   enabled: true

# Vault UI
# ui:
#   enabled: true
#   serviceType: "LoadBalancer"
#   serviceNodePort: null
#   externalPort: 8200

# ui:
#   enabled: true
#   serviceType: "ClusterIP"

ui:
  enabled: true
  serviceType: ClusterIP