# These Resource Limits are in line with node requirements in the
# Vault Reference Architecture for a Small Cluster
server:
  resources:
    requests:
      memory: 2Gi
      cpu: 250m
    limits:
      memory: 4Gi
      cpu: 250m
    
  # dev:
  #   enabled: true

# Vault UI
# ui:
#   enabled: true
#   serviceType: "LoadBalancer"
#   serviceNodePort: null
#   externalPort: 8200

# ui:
#   enabled: true
#   serviceType: "ClusterIP"

ui:
  enabled: true
  serviceType: ClusterIP