apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-nfs-backup-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    #path: /export/vault-backups
    server: 10.7.7.110
  storageClassName: vault-nfs
