apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-nfs-pvc
  namespace: vault
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: vault-nfs
  resources:
    requests:
      storage: 1Gi
