---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-narybits-site
  namespace: default
spec:
  secretName: local-narybits-site-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.narybits.site"
  dnsNames:
  - "local.narybits.site"
  - "*.local.narybits.site"
