apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-database
  namespace: database
spec:
  instances: 3

  storage:
    #storageClass: nfs-storage
    size: 10Gi
